version: 2.1

jobs:
  deploy-n8n-workflow:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Descargar workflow desde GitHub
          command: |
            curl -L -o workflow.json https://raw.githubusercontent.com/smentz1/n8n-CCI-restore/main/workflows/workflow.json
      - run:
          name: Desplegar workflow a n8n
          command: |
            curl -X POST "$N8N_URL/api/v1/workflows" \
              -H "Content-Type: application/json" \
              -H "X-N8N-API-KEY: $N8N_API_KEY" \
              -d @workflow.json

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-n8n-workflow
